spring.application.name=mzansi-builds-api

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5434/mzansi_builds
spring.datasource.username=postgres
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=Sonke.$$001.1032y485h-this-is-a-much-longer-secret-key-for-jwt-tokens-that-meets-the-256-bit-requirement
jwt.expiration=86400000


logging.level.root=INFO
logging.level.com.mzansibuilds=DEBUG
