spring.application.name=mzansi-builds-api

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5434/mzansi_builds
spring.datasource.username=postgres
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=3d62c07a3f8b6f4fa8d2f1c7e0b9a4d8e7f6c1a2b3d4e5f6
jwt.expiration=86400000


logging.level.root=INFO
logging.level.com.mzansibuilds=DEBUG
