spring.application.name=mzansi-builds-api

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5434/mzansi_builds
spring.datasource.username=postgres
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=d9f4c8b2e7a1f3c5d6e8b0a2c4f6d8e0a1b3c5d7e9f1a2b4c6d8e0f2a4b6c8
jwt.expiration=86400000


logging.level.root=INFO
logging.level.com.mzansibuilds=DEBUG
